set hlsearch	
set smartcase 
set ignorecase
set incsearch	

" fuzzy find
set path+=**
set wildmenu

":b find in buffer
 
"set tag? show tags
"echo expand("%")

set autoindent
set shiftwidth=4	
"set smartindent
set smarttab
set expandtab
set softtabstop=4
set shiftwidth=2
set clipboard=unnamed
set backspace=indent,eol,start
set hidden
set showcmd


"set rtp+=/usr/local/opt/fzf


let g:netrw_banner=0        " disable annoying banner
let g:netrw_browse_split=4  " open in prior window
let g:netrw_altv=1          " open splits to the right
let g:netrw_liststyle=3     " tree view
let g:netrw_list_hide=netrw_gitignore#Hide()
let g:netrw_list_hide.=',\(^\|\s\s\)\zs\.\S\+'
highlight Pmenu ctermfg=magenta ctermbg=blue
highlight PmenuSel ctermfg=darkred ctermbg=blue



nmap <silent> <Leader>d :!dict<CR>
nmap <silent> <Leader>m- 3i-<ESC>
nnoremap <leader>m :silent !open -a Marked\ 2.app '%:p'<cr>
nmap <silent> <leader>da <Plug>DashSearch


"inoremap " ""<left>
"inoremap ' ''<left>
"inoremap ( ()<left>
"inoremap [ []<left>
"inoremap { {}<left>
"inoremap {<CR> {<CR>}<ESC>O

function! Json()
    set filetype=json
    set fdm=syntax
    syntax on
    echo "json on"
endfunction

command! Json call Json()

autocmd BufNewFile,BufRead *.json set ft=javascript


" Create the `tags` file (may need to install ctags first)
command! MakeTags !ctags -R .

" - Use ^] to jump to tag under cursor
" - Use g^] for ambiguous tags
" - Use ^t to jump back up the tag stack
